apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-config
data:
  main_01_input.conf: |
    input {
      beats {
        port => 5044
      }
    }
  main_02_filter.conf: |
    filter {
      json {
        id => "message_json_parse"
        source => "message"
        target => "json_log"
      }
    }
  main_03_output.conf: |
    output {
      stdout {
        codec => rubydebug
      }
    }
  audit.conf: |
    input {
      syslog {
        port => 12345
      }
    }
    output {
      stdout {
        codec => rubydebug
      }
    }