apiVersion: v1
kind: Service
metadata:
  name: {{ include "dream-app.fullname" . }}
  labels:
    {{- include "dream-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "dream-app.selectorLabels" . | nindent 4 }}
