logstash:
  extraVolumes:
  - name: logstash-config
    configMap:
      name: logstash-config
      items:
        - key: logstash.yml
          path: logstash.yml
        - key: pipelines.yml
          path: pipelines.yml

  - name: pipelines
    configMap:
      name: pipeline-config

  extraVolumeMounts:
  - name: logstash-config
    mountPath: /usr/share/logstash/config/logstash.yml
    subPath: logstash.yml
  - name: logstash-config
    mountPath: /usr/share/logstash/config/pipelines.yml
    subPath: pipelines.yml
  - name: pipelines
    mountPath: /usr/share/logstash/pipeline
  
  secretMounts: 
  - name: ca
    secretName: elasticsearch-master-certs
    path: /usr/share/logstash/config/credentials