- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/master, tags: master }
    - { role: cni, tags: cni }

- hosts: node
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/node, tags: node }
    - { role: cni, tags: cni }

- hosts: docker-node
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/node, tags: node }
    - { role: cni, tags: cni }
    - { role: docker, tags: docker }