pipeline {
    agent {
        docker {
            image 'ubuntu:22.04'
        }
    }
    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
    }
    environment {
        DOCKERHUB_CREDENTIALS = credentials('0a800395-9183-4b58-99fb-19cd25f6acf9')
    }
    stages {
        stage('Prebuild') {
            steps{
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: '.']], submoduleCfg: [], userRemoteConfigs: [[url: 'https://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@github.com/aviatus/dream-case.git']]])
            }
        }
        stage('Build') {
            environment {
                REPOSITORY_URI = 'aviatus/dream-case'
            }
            steps {
                echo 'Building started...'
                sh 'cd app'
                sh 'docker build -f Dockerfile -t $REPOSITORY_URI:latest .'
                sh 'docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG'
            }
        }
        stage('Deploy Docker') {
            steps {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                echo 'Deploying started.'
            }
        }
        stage('Deploy Kubernetes') {
            steps {
                sh 'curl -L https://git.io/get_helm.sh | bash -s -- --version v3.8.2'
                echo 'Deploy k8s'   
            }
        }
    }
}
