apiVersion: v2
name: elastic-search
description: A Helm chart for Kubernetes Elastic Search
type: application

version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: elasticsearch
    version: "8.5.1"
    repository: "https://helm.elastic.co"